name: Ask a question, any question!
description: Need support? We are here to help!
labels:
  - support
body:
  - type: input
    attributes:
      label: Runtime
      description: (e.g. node.js, browser, ...)
    validations:
      required: true
  - type: input
    attributes:
      label: Runtime version
    validations:
      required: true
  - type: input
    attributes:
      label: Module version
    validations:
      required: true
  - type: input
    attributes:
      label: Used with
      description: (e.g. hapi application, another framework, standalone, ...)
  - type: textarea
    attributes:
      label: Any other relevant information
  - type: textarea
    attributes:
      label: How can we help?
      description: Describe your question in detail, including what you have already tried, or any configuration, schemas, code samples, or inputs needed. Make sure to wrap all code examples in backticks so that they display correctly. Before submitting an issue, make sure to click on the Preview tab to verify everything is formatted correctly.
      value: |
        ```js
        const some = 'properly formatted code example';
        ```
    validations:
      required: true
