name: Bug report
description: Report issues with existing functionality
labels:
  - bug
body:
  - type: input
    attributes:
      label: Runtime
      description: (e.g. node.js, browser, ...)
    validations:
      required: true
  - type: input
    attributes:
      label: Runtime version
    validations:
      required: true
  - type: input
    attributes:
      label: Module version
    validations:
      required: true
  - type: input
    attributes:
      label: Last module version without issue
  - type: input
    attributes:
      label: Used with
      description: (e.g. hapi application, another framework, standalone, ...)
  - type: textarea
    attributes:
      label: Any other relevant information
  - type: textarea
    attributes:
      label: What are you trying to achieve or the steps to reproduce?
      description: Describe your issue in detail, including full steps to reproduce the issue, any configuration, schemas, code samples, or inputs needed. Make sure to wrap all code examples in backticks so that they display correctly. Before submitting an issue, make sure to click on the Preview tab to verify everything is formatted correctly.
    validations:
        required: true
  - type: textarea
    attributes:
      label: What was the result you got?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What result did you expect?
    validations:
      required: true
