name: ci

on:
  workflow_call:
    inputs:
      min-node-version:
        description: 'The minimum version of nodejs with which to run the workflow'
        type: number
        required: false

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        node: ${{ inputs.min-node-version == 14 && fromJSON('["*", "16", "14"]') || fromJSON('["16", "14", "12"]') }}

    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }} node@${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: ${{ matrix.node == '*' }}
      - name: install
        run: npm install
      - name: test
        run: npm test
